server:
  port: 8001

spring:
  application:
    name: cloud-stream-provider
  cloud:
    stream:
      binders: # 配置需要绑定的RabbitMQ的服务信息
        defaultRabbit: # 表示定义的名称，用于binding的整合
          type: rabbit # 消息组件类型
          environment: # 配置RabbitMQ的环境
            spring:
              rabbitmq:
                host: 192.168.0.12
                username: guest
                password: guest
                port: 5672
      # 服务的整合处理
      bindings:
        output: # 生产者
          destination: studyExchange      # Exchange名称
          content-type: application/json # 设置消息类型，使用json，文本数据使用"text/plain"
          binder: defaultRabbit       # 设置需要绑定哪一个消息服务(对应消息服务名)
  rabbitmq:
    host: 192.168.0.12

eureka:
  instance:
    prefer-ip-address: true
    instance-id: send-8801.com
    lease-renewal-interval-in-seconds: 2
    lease-expiration-duration-in-seconds: 5
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
