server:
  port: 8001

spring:
  application:
    name: cloud-hystrix-payment-service

eureka:
  instance:
    instance-id: cloud-payment-8001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/