server:
  port: 7001

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      # defaultZone: http://eureka7002.com:7002/eureka/ 集群模式
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    hostname: eureka7001.com
  server:
    enable-self-preservation: false # 禁用自我保护机制
    eviction-interval-timer-in-ms: 2000
